=== SaRaHussien2/XML/rss.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT rss (channel+) >
<!ELEMENT channel (title,description,link,item+)>
<!ELEMENT  item (title,description,link)>

<!ELEMENT  title (#PCDATA)>
<!ELEMENT  description (#PCDATA)>
<!ELEMENT  link (#PCDATA)>

<!ATTLIST rss  version  CDATA #IMPLIED>

=== SaRaHussien2/XML/rss.xml
<?xml version="1.0" encoding="UTF-8"?>
 <!-- <!DOCTYPE rss SYSTEM "rss.dtd"> -->
 <rss xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="rss.xsd"> 

	<channel>
	    <title>Webster University</title>
	    <description>Home Page of Webster University</description>
	    <link>http://www.webster.edu</link>
	    <item>
		    <title>Webster Univ. Geneva</title>
			<description>Home page of Webster University Geneva</description>
		    <link>http://www.webster.ch</link>
        </item>
        <item>
		    <title>http://www.course.com/</title>
		    <description>You can find Thomson text-books materials (exercise data) on this web site</description>
		    <link>http://www.course.com/</link>
        </item>
    </channel>
</rss>
